server:
    port: 9090
    address: localhost

spring:
    data:
        cassandra:
            port: 9942
            keyspace-name: SSD.TABLETS
            contact-points: 10.254.5.1, 10.254.5.2, 10.254.5.3
            local-datacenter: datacenter1
            schema-action: CREATE_IF_NOT_EXISTS

            request:
                timeout: 10s
                consistency: quorum

            connection:
                connect-timeout: 10s
                init-query-timeout: 10s

    rsocket:
        server:
            port: 6060
            address: localhost

variables:
    KAFKA_BROKER: 10.254.6.1:9092, 10.254.6.2:9092, 10.254.6.3:9092
    GROUP_ID_FOR_KAFKA: SSD.GPS.DATA.TEST

    NEW_CAR_TOPIC: NEW_CAR_TOPIC_DEV
    NEW_TUPLE_OF_CAR_TOPIC: newTupleOfCarTopicDev
    RAW_GPS_LOCATION_TOPIC: RAW_GPS_LOCATION_TOPIC_DEV
    TUPLE_OF_CAR_LOCATION_TOPIC: TUPLE_OF_CAR_LOCATION_TOPIC_DEV
    WEBSOCKET_SERVICE_TOPIC_FOR_ONLINE: webSocketServiceTopicForOnlineDev

    CASSANDRA_PORT: 9942

    CASSANDRA_MAX_CONN_LOCAL: 10
    CASSANDRA_MAX_CONN_REMOTE: 4

    CASSANDRA_CORE_CONN_LOCAL: 4
    CASSANDRA_CORE_CONN_REMOTE: 2

    ADDRESS_LOCATION_API : http://ms-dev.ssd.uz/nominatim/search?q=
