server:
    port: ${SERVER_PORT:9090}
    address: ${SERVER_ADDR:localhost}

spring:
    data:
        cassandra:
            port: ${CASSANDRA_PORT:9942}
            keyspace-name: ${KEYSPACE_NAME:GpsTracker}
            contact-points: ${CASSANDRA_HOST:10.254.5.1, 10.254.5.2, 10.254.5.3}
            local-datacenter: ${CASSANDRA_DC:datacenter1}
            schema-action: CREATE_IF_NOT_EXISTS

            request:
                timeout: ${REQUEST_TIMEOUT_FOR_CASSANDRA:30000}
                consistency: quorum

            connection:
                connect-timeout: ${CONNECTION_TIMEOUT_FOR_CASSANDRA:60000}
                init-query-timeout: ${INIT_QUERY_TIMEOUT_FOR_CASSANDRA:60000}

    rsocket:
        server:
            port: ${RSOCKET_PORT:6060}
            address: ${SERVER_ADDR:localhost}

variables:
    KAFKA_VARIABLES:
        KAFKA_BROKER: ${KAFKA_BROKER:localhost:9092}
        GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA:SSD.GPS.DATA.DEV.TEST}

        KAFKA_TOPICS:
            NEW_CAR_TOPIC: ${NEW_CAR_TOPIC:NEW_CAR_TOPIC_DEV}
            NEW_TUPLE_OF_CAR_TOPIC: ${NEW_TUPLE_OF_CAR_TOPIC:newTupleOfCarTopicDev}
            RAW_GPS_LOCATION_TOPIC: ${RAW_GPS_LOCATION_TOPIC:RAW_GPS_LOCATION_TOPIC_DEV}
            TUPLE_OF_CAR_LOCATION_TOPIC: ${TUPLE_OF_CAR_LOCATION_TOPIC:TUPLE_OF_CAR_LOCATION_TOPIC_DEV}
            WEBSOCKET_SERVICE_TOPIC_FOR_ONLINE: ${WEBSOCKET_SERVICE_TOPIC_FOR_ONLINE:webSocketServiceTopicForOnlineDev}

    KEYSPACE_NAME : ${KEYSPACE_NAME:MyCassandra}
    CASSANDRA_PORT: ${CASSANDRA_PORT:9042}

    CASSANDRA_MAX_CONN_LOCAL: ${CASSANDRA_MAX_CONN_LOCAL:10}
    CASSANDRA_MAX_CONN_REMOTE: ${CASSANDRA_MAX_CONN_REMOTE:4}

    CASSANDRA_CORE_CONN_LOCAL: ${CASSANDRA_CORE_CONN_LOCAL:4}
    CASSANDRA_CORE_CONN_REMOTE: ${CASSANDRA_CORE_CONN_REMOTE:2}

    ADDRESS_LOCATION_API : http://ms-dev.ssd.uz/nominatim/search?q=