server:
    port: ${SERVER_PORT}
    address: ${SERVER_ADDR}

spring:
    data:
        cassandra:
            port: ${CASSANDRA_PORT}
            keyspace-name: ${KEYSPACE_NAME}
            contact-points: ${CASSANDRA_HOST}
            local-datacenter: ${CASSANDRA_DC}
            schema-action: CREATE_IF_NOT_EXISTS

            request:
                timeout: ${REQUEST_TIMEOUT_FOR_CASSANDRA}
                consistency: quorum

            connection:
                connect-timeout: ${CONNECTION_TIMEOUT_FOR_CASSANDRA}
                init-query-timeout: ${INIT_QUERY_TIMEOUT_FOR_CASSANDRA}

    rsocket:
        server:
            port: ${RSOCKET_PORT}
            address: ${SERVER_ADDR}

variables:
    KAFKA_VARIABLES:
        KAFKA_BROKER: ${KAFKA_BROKER}
        GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA:SSD.GPS.DATA}

        KAFKA_TOPICS:
            NEW_CAR_TOPIC: ${NEW_CAR_TOPIC:newCarTopic}
            NEW_TUPLE_OF_CAR_TOPIC: ${NEW_TUPLE_OF_CAR_TOPIC:newTupleOfCarTopic}
            RAW_GPS_LOCATION_TOPIC: ${RAW_GPS_LOCATION_TOPIC:RAW_GPS_LOCATION_TOPIC_PROD}
            TUPLE_OF_CAR_LOCATION_TOPIC: ${TUPLE_OF_CAR_LOCATION_TOPIC:tupleOfCarLocationTopic}
            WEBSOCKET_SERVICE_TOPIC_FOR_ONLINE: ${WEBSOCKET_SERVICE_TOPIC_FOR_ONLINE:webSocketServiceTopicForOnline}

    KEYSPACE_NAME : ${KEYSPACE_NAME:GpsTracker}
    CASSANDRA_PORT: ${CASSANDRA_PORT:9942}

    CASSANDRA_MAX_CONN_LOCAL: ${CASSANDRA_MAX_CONN_LOCAL:10}
    CASSANDRA_MAX_CONN_REMOTE: ${CASSANDRA_MAX_CONN_REMOTE:4}

    CASSANDRA_CORE_CONN_LOCAL: ${CASSANDRA_CORE_CONN_LOCAL:4}
    CASSANDRA_CORE_CONN_REMOTE: ${CASSANDRA_CORE_CONN_REMOTE:2}

    ADDRESS_LOCATION_API : http://ms-dev.ssd.uz/nominatim/search?q=