server:
    port: ${SERVER_PORT:9090}
    address: ${SERVER_ADDR:localhost}

spring:
    data:
        cassandra:
            port: ${CASSANDRA_PORT:9942}
            keyspace-name: ${KEYSPACE_NAME:GpsTracker}
            contact-points: ${CASSANDRA_HOST}
            local-datacenter: ${CASSANDRA_DC}
            schema-action: CREATE_IF_NOT_EXISTS

            request:
                timeout: ${REQUEST_TIMEOUT_FOR_CASSANDRA:30000}
                consistency: quorum

            connection:
                connect-timeout: ${CONNECTION_TIMEOUT_FOR_CASSANDRA:60000}
                init-query-timeout: ${INIT_QUERY_TIMEOUT_FOR_CASSANDRA:60000}

    rsocket:
        server:
            port: ${RSOCKET_PORT:6060}
            address: ${SERVER_ADDR:localhost}

variables:
    KAFKA_VARIABLES:
        KAFKA_BROKER: ${KAFKA_BROKER:localhost:9092}
        GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA:SSD.GPS.DATA.DEV.TEST}

        KAFKA_TOPICS:
            NEW_CAR_TOPIC: ${NEW_CAR_TOPIC:NEW_CAR_TOPIC_DEV}
            NEW_TUPLE_OF_CAR_TOPIC: ${NEW_TUPLE_OF_CAR_TOPIC:newTupleOfCarTopicDev}
            RAW_GPS_LOCATION_TOPIC: ${RAW_GPS_LOCATION_TOPIC:RAW_GPS_LOCATION_TOPIC_DEV}
            TUPLE_OF_CAR_LOCATION_TOPIC: ${TUPLE_OF_CAR_LOCATION_TOPIC:TUPLE_OF_CAR_LOCATION_TOPIC_DEV}
            WEBSOCKET_SERVICE_TOPIC_FOR_ONLINE: ${WEBSOCKET_SERVICE_TOPIC_FOR_ONLINE:webSocketServiceTopicForOnlineDev}

    #   https://docs.datastax.com/en/developer/java-driver/3.6/manual/pooling/index.html
    CASSANDRA_VARIABLES:
        CASSANDRA_PORT: ${CASSANDRA_PORT:9042}
        CASSANDRA_HOST: ${CASSANDRA_HOST:localhost}
        CASSANDRA_CLUSTER_NAME: ${CASSANDRA_CLUSTER_NAME:TEST_CLUSTER}

        CASSANDRA_MAX_REQ: ${CASSANDRA_MAX_REQ:1000}
        CASSANDRA_MAX_CONN_LOCAL: ${CASSANDRA_MAX_CONN_LOCAL:10}
        CASSANDRA_MAX_CONN_REMOTE: ${CASSANDRA_MAX_CONN_REMOTE:4}

        CASSANDRA_CORE_CONN_LOCAL: ${CASSANDRA_CORE_CONN_LOCAL:4}
        CASSANDRA_CORE_CONN_REMOTE: ${CASSANDRA_CORE_CONN_REMOTE:2}

        CASSANDRA_READ_TIMEOUT_IN_MILLIS: ${CASSANDRA_READ_TIMEOUT_IN_MILLIS:3000}
        CASSANDRA_CONNECTION_TIMEOUT_IN_MILLIS: ${CASSANDRA_CONNECTION_TIMEOUT_IN_MILLIS:30000}

        CASSANDRA_IDLE_CONN_TIME_IN_SECONDS: ${CASSANDRA_IDLE_CONN_TIME_IN_SECONDS:15}
        CASSANDRA_HEARTBEAT_INTERVAL_IN_SECONDS: ${CASSANDRA_HEARTBEAT_INTERVAL_IN_SECONDS:60}

        CASSANDRA_MAX_REQUESTS_PER_CONNECTION_LOCAL: ${CASSANDRA_MAX_REQUESTS_PER_CONNECTION_LOCAL:32768}
        CASSANDRA_MAX_REQUESTS_PER_CONNECTION_REMOTE: ${CASSANDRA_MAX_REQUESTS_PER_CONNECTION_REMOTE:2000}

        CASSANDRA_RETRY_READ_ATTEMPTS: ${CASSANDRA_RETRY_READ_ATTEMPTS:3}
        CASSANDRA_RETRY_WRITE_ATTEMPTS: ${CASSANDRA_RETRY_WRITE_ATTEMPTS:3}
        CASSANDRA_RETRY_UNAVAILABLE_ATTEMPTS: ${CASSANDRA_RETRY_RUNAVAILABLEATTEMPTS:2}

    KEYSPACE_NAME : ${KEYSPACE_NAME:MyCassandra}
    CASSANDRA_PORT: ${CASSANDRA_PORT:9042}

    CASSANDRA_MAX_CONN_LOCAL: ${CASSANDRA_MAX_CONN_LOCAL:10}
    CASSANDRA_MAX_CONN_REMOTE: ${CASSANDRA_MAX_CONN_REMOTE:4}

    CASSANDRA_CORE_CONN_LOCAL: ${CASSANDRA_CORE_CONN_LOCAL:4}
    CASSANDRA_CORE_CONN_REMOTE: ${CASSANDRA_CORE_CONN_REMOTE:2}

    ADDRESS_LOCATION_API : ${ADDRESS_LOCATION_API}