package com.ssd.mvd.constants;

public enum CassandraTables {
    // tables for CRUD
    TABLETS,
    REPORT_FOR_CARD, POLYGON_FOR_PATRUl,
    CARS, LUSTRA, PATRULS, POLYGON, NOTIFICATION, PATRULS_LOGIN_TABLE, PATRULS_STATUS_TABLE,
    PATRUL_TYPE, POLICE_TYPE, CAMERA_LIST, POLYGON_TYPE, POLYGON_ENTITY, VIOLATION_LIST_TYPE,

    // tables for ESCORT Entity
    ESCORT,
    COUNTRIES, TUPLE_OF_CAR, TUPLE_OF_ESCORT, POINTS_ENTITY, POLYGON_FOR_ESCORT, ESCORT_LOCATION,

    TRACKERS,
    TRACKERS_LOCATION_TABLE, TRACKERSID, TRACKER_FUEL_CONSUMPTION,
}
